### ISSUE TITLE
clarify license to public domain

### ISSUE THREAD

**Issue by avsm** [mirage/xen-arm-builder#42]
We need to clarify the license on the shell scripts.  Since they're so commonly cut-and-pasted, I'd just like to propose a public domain CC0 license for simplicity.  If you've contributed, could you please acknowledge this here in the comments field that you are ok for your patch to be under the CC0 license?

- [x] @avsm
- [x] @Chris00 
- [x] @dsheets 
- [x] @jonludlam 
- [x] @MagnusS 
- [x] @samoht 
- [x] @talex5 

thanks!

**Comment by avsm** [comment]
Ping, @MagnusS ...

**Comment by MagnusS** [comment]
I agree for my contributions to be licensed under the CC0

**Comment by avsm** [comment]
Thanks everyone!
