### ISSUE TITLE
unable to get domain type on ARM

### ISSUE THREAD

**Issue by heidi-ann** [mirage/xen-arm-builder#46]
I'm often getting the following in response to running xl create on cubieboard2, for example...
any advise on where to start debugging this?

```
$ sudo xl create -c stackv4.xl
Parsing config from stackv4.xl
libxl: error: libxl_dom.c:35:libxl__domain_type: unable to get domain type for domid=2
Unable to attach console
libxl: error: libxl_exec.c:118:libxl_report_child_exitstatus: console child [0] exited with error status 1
``

**Comment by avsm** [comment]
out of memory?

**Comment by heidi-ann** [comment]
nope, only got dom-0 running, using 512

**Comment by avsm** [comment]
no VIF in the xl configuration file then.

**Comment by talex5** [comment]
This means the unikernel exited before dom0 could attach the console. Add this to the Xen config file to see the real error:

    on_poweroff = 'preserve'

**Comment by heidi-ann** [comment]
thanks guys, @avsm was right about the stack4 example and @talex5 that does give more information, in some of the other examples

**Comment by avsm** [comment]
heidi -- any chance you could write a quick FAQ about this (a couple of paras is fine) -- can stick it into a 'common errors on xen arm blog post'

**Comment by heidi-ann** [comment]
ok, will do

**Comment by talex5** [comment]
Actually, I think we could just fix this rather than documenting it (not tested yet):

https://github.com/talex5/mirage-platform/commits/exit-status

**Comment by avsm** [comment]
This will be in mirage-xen.2.1.3 in ocaml/opam-repository#3443

**Comment by heidi-ann** [comment]
I'm updating now, I'm still seeing this issue for unikernels with block devices, see xl file below so hopefully this update will help debug this:
```
cat block_test.xl
# Generated by Mirage (Thu, 1 Jan 1970 00:18:27 GMT).

name = 'block_test'
kernel = '/home/mirage/mirage-skeleton/block/mir-block_test.xen'
builder = 'linux'
memory = 256
on_crash = 'preserve'

# You must define the network and block interfaces manually.

# The disk configuration is defined here:
# http://xenbits.xen.org/docs/4.3-testing/misc/xl-disk-configuration.txt
# An example would look like:
disk = [ '/dev/loop0,,xvda1,w']
```

**Comment by heidi-ann** [comment]
fix seems to working for me, gone from the previous error to 
```
Block.connect /home/mirage/mirage-skeleton/block/disk.img: unable to match '/home/mirage/mirage-skeleton/block/disk.img' to any available devices [ 51713 ]
Block.connect /home/mirage/mirage-skeleton/block/disk.img: could not find device
Fatal error: exception Failure("block1")
Raised at file "src/core/lwt.ml", line 788, characters 22-23
Called from file "main.ml", line 31, characters 2-28
Mirage exiting with status 2
```

which is much more helpful

Thanks guys :)
