### ISSUE TITLE
add NTP daemon to image

### ISSUE THREAD

**Issue by heidi-ann** [mirage/xen-arm-builder#48]
not currently included and would be useful :)

**Comment by djs55** [comment]
I've noticed (several times now, grr) that if the system clock is set to 1970 then `opam install` will block forever -- I believe it will download ocamlfind, unpack it with timestamps from 2015, build an object file with timestamp in 1970, ocamlbuild (or make, not sure) will conclude that the object file is 45 years old and rebuild it, again and again. 

Even without an ntp daemon, a one-shot sync to pool.ntp.org would make life a lot better.

**Comment by avsm** [comment]
@heidi-ann -- could you take a shot at a pull request to add this?  It should be a case of adding the right ntp daemon to the `apt-get` install list in the scripts here, and the builder will pick it up.

**Comment by MagnusS** [comment]
Another problem when this happens is that a log-file is generated which can fill the SD-card if left running too long. Should be straightforward to add ntp I think. [This](https://github.com/mirage/xen-arm-builder/blob/master/build.sh) is the script that installs the other packages.

**Comment by heidi-ann** [comment]
I don't have access to a cubie until tus, but i'll take a look then

**Comment by samoht** [comment]
Can also help fixing:

```
$ git clone https://github.com/samoht/mirage-seal.git
Cloning into 'mirage-seal'...
fatal: unable to access 'https://github.com/samoht/mirage-seal.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```

(which was fixed by `sudo ntpdate -s time.nist.gov`)

**Comment by mor1** [comment]
The recent refresh installs and starts `chronyd` to handle NTP so hopefully this is no longer an issue. Closing...
