### ISSUE TITLE
Installing on Nokia E71

### ISSUE THREAD

**Issue by amitai-hoze** [mirage/xen-arm-builder#56]
Hi, I have a Nokia E71 lying around, and was wondering if I can install a xen hypervisor and a mirage unikernel on it.. Can I?

**Comment by amirmc** [comment]
Getting MirageOS working on a mobile device/phone would be pretty cool but my guess is that wouldn’t work with the E71 [1].  The hardware is quite old and likely not able to run Xen as required. There are probably a lot of other issues with trying to use an old phone handset as a dev environment.

We use the Cubieboard2 (and CubeTruck) [2] as our ARM dev environments and I’d suggest you consider those.  The prebuilt images from http://blobs.openmirage.org make it much quicker to get started (and are based on this repo).

[1] http://www.gsmarena.com/nokia_e71-2425.php
[2] http://cubieboard.org
