### ISSUE TITLE
Question about making iso for ARM devices on travis-ci

### ISSUE THREAD

**Issue by show0k** [mirage/xen-arm-builder#59]
Hi,
I thought it wasn't possible to mount and chroot in a ARM arch with travis because of [limitation of OpenVZ kernel](https://github.com/travis-ci/travis-ci/issues/1119). Do you really manage to create iso for cubie-board with travis-ci ?
Thanks for your help

**Comment by talex5** [comment]
It looks like the Travis script stops before building the ISO itself:

https://github.com/mirage/xen-arm-builder/commit/f37154bc42a66060aef0527713beade938bb98e3
