### ISSUE TITLE
CubieTruck pre-built image not booting up

### ISSUE THREAD

**Issue by vitcozzolino** [mirage/xen-arm-builder#63]
Hi,
I've flashed my SDcard with the prebuilt image for cubietruck but apparently it's not working. The board just get stuck during the boot-up phase and doesn't even try to switch to the NAND OS when the SDcard is inserted. With different images the boards can boot up normally from the SDcard.

Will try now to create an image from source.

**Comment by talex5** [comment]
Did the source version work?

**Comment by vitcozzolino** [comment]
Hello,
same problem also with the image built from source.

**Comment by talex5** [comment]
Found my serial cable. With today's cubietruck image:

    U-Boot SPL 2015.04 (Jul 08 2015 - 09:11:37)
    DRAM: 2048 MiB
    CPU: 912000000Hz, AXI/AHB/APB: 3/2/2


    U-Boot 2015.04 (Jul 08 2015 - 09:11:37) Allwinner Technology

    CPU:   Allwinner A20 (SUN7I)
    I2C:   ready
    DRAM:  2 GiB
    MMC:   SUNXI SD/MMC: 0
    *** Warning - bad CRC, using default environment

    Setting up a 1024x768 vga console
    In:    serial
    Out:   vga
    Err:   vga
    SCSI:  SUNXI SCSI INIT
    SATA link 0 timeout.
    AHCI 0001.0100 32 slots 1 ports 3 Gbps 0x1 impl SATA mode
    flags: ncq stag pm led clo only pmp pio slum part ccc apst
    Net:   dwmac.1c50000
    starting USB...
    USB0:   USB EHCI 1.00
    scanning bus 0 for devices... 1 USB Device(s) found
    USB1:   USB EHCI 1.00
    scanning bus 1 for devices... 1 USB Device(s) found
	   scanning usb for storage devices... 0 Storage Device(s) found
    Hit any key to stop autoboot:  0
    switch to partitions #0, OK
    mmc0 is current device
    Scanning mmc 0:1...
    Found U-Boot script /boot.scr
    reading /boot.scr
    1629 bytes read in 22 ms (72.3 KiB/s)
    ## Executing script at 43100000
    reading /xen
    688912 bytes read in 59 ms (11.1 MiB/s)
    reading /sun7i-a20-cubietruck.dtb
    21639 bytes read in 30 ms (704.1 KiB/s)
    reading /vmlinuz
    5247808 bytes read in 274 ms (18.3 MiB/s)
    Kernel image @ 0xaea00000 [ 0x000000 - 0x0ef700 ]
    ## Flattened Device Tree blob at aec00000
       Booting using the fdt blob at 0xaec00000
       reserving fdt memory region: addr=aec00000 size=6000
       Using Device Tree in place at aec00000, end aec08fff
    Cannot setup simplefb: node not found

    Starting kernel ...

    - UART enabled -
    - CPU 00000000 booting -
    - Xen starting in Hyp mode -
    - Zero BSS -
    - Setting up control registers -
    - Turning on paging -
    - Ready -
    Checking for initrd in /chosen
    RAM: 0000000040000000 - 00000000bfffffff

    MODULE[1]: 00000000aec00000 - 00000000aec06000
    MODULE[2]: 00000000af600000 - 00000000afb01340 console=hvc0 ro root=/dev/mmcblk0p2 rootwait clk_ignore_unused
     RESVD[0]: 00000000aec00000 - 00000000aec06000

    Command line: console=dtuart dtuart=/soc@01c00000/serial@01c28000 dom0_mem=512M,max:512M
    Placing Xen at 0x00000000bfe00000-0x00000000c0000000
    Xen heap: 000000009e000000-00000000ae000000 (65536 pages)
    Dom heap: 458752 pages
    Looking for UART console /soc@01c00000/serial@01c28000
     Xen 4.4.1-rc1
    (XEN) Xen version 4.4.1-rc1 (@) (arm-linux-gnueabihf-gcc (Ubuntu/Linaro 4.8.2-16ubuntu4) 4.8.2) debug=y Wed Jul  8 09:11:51 UTC 2015
    (XEN) Latest ChangeSet: Fri Aug 1 18:59:35 2014 +0100 git:a63eb05
    (XEN) Processor: 410fc074: "ARM Limited", variant: 0x0, part 0xc07, rev 0x4
    (XEN) 32-bit Execution:
    (XEN)   Processor Features: 00001131:00011011
    (XEN)     Instruction Sets: AArch32 Thumb Thumb-2 ThumbEE Jazelle
    (XEN)     Extensions: GenericTimer Security
    (XEN)   Debug Features: 02010555
    (XEN)   Auxiliary Features: 00000000
    (XEN)   Memory Model Features: 10101105 40000000 01240000 02102211
    (XEN)  ISA Features: 02101110 13112111 21232041 11112131 10011142 00000000
    (XEN) Platform: Allwinner A20
    (XEN) Using PSCI for SMP bringup
    (XEN) Generic Timer IRQ: phys=30 hyp=26 virt=27
    (XEN) Using generic timer at 24000 KHz
    (XEN) GIC initialization:
    (XEN)         gic_dist_addr=0000000001c81000
    (XEN)         gic_cpu_addr=0000000001c82000
    (XEN)         gic_hyp_addr=0000000001c84000
    (XEN)         gic_vcpu_addr=0000000001c86000
    (XEN)         gic_maintenance_irq=25
    (XEN) GIC: 160 lines, 2 cpus, secure (IID 0100143b).
    (XEN) Using scheduler: SMP Credit Scheduler (credit)
    (XEN) Allocated console ring of 16 KiB.
    (XEN) VFP implementer 0x41 architecture 2 part 0x30 variant 0x7 rev 0x4
    (XEN) Bringing up CPU1
    - CPU 00000001 booting -
    - Xen starting in Hyp mode -
    - Setting up control registers -
    - Turning on paging -
    - Ready -
    (XEN) CPU 1 booted.
    (XEN) Brought up 2 CPUs
    (XEN) CPU0: Unexpected Trap: Data Abort
    (XEN) ----[ Xen-4.4.1-rc1  arm32  debug=y  Not tainted ]----
    (XEN) CPU:    0
    (XEN) PC:     00271038 cpu_stopmachine_init+0x80/0x110
    (XEN) CPSR:   0000005a MODE:Hypervisor
    (XEN)      R0: 002ee2f0 R1: 002bae85 R2: 002469e0 R3: 002bae85
    (XEN)      R4: 002469e0 R5: 6000005a R6: 00267ccc R7: 002a7e94
    (XEN)      R8: 002bae86 R9: 002a7e94 R10:00000080 R11:002a7e9c R12:00000001
    (XEN) HYP: SP: 002a7e7c LR: 0027102c
    (XEN)
    (XEN)   VTCR_EL2: 80002558
    (XEN)  VTTBR_EL2: 000000e03290fdc0
    (XEN)
    (XEN)  SCTLR_EL2: 30cd187f
    (XEN)    HCR_EL2: 000000000038283f
    (XEN)  TTBR0_EL2: 00000000bfee7000
    (XEN)
    (XEN)    ESR_EL2: 94000021
    (XEN)  HPFAR_EL2: 000000008ab368c0
    (XEN)      HDFAR: 6000005a
    (XEN)      HIFAR: 140812a0
    (XEN)
    (XEN) Xen stack trace from sp=002a7e7c:
    (XEN)    0027102c 00000005 002a8308 00000007 002ec254 002ec264 00000002 002a7eb4
    (XEN)    00270098 00000080 00000080 0026cb80 002ec254 002a7f54 0027a590 11112131
    (XEN)    10011142 00000000 00000000 00000000 00000000 bfe00000 00000000 00000000
    (XEN)    adff9000 40000000 00000000 00000001 00288020 c0000000 00000000 00270580
    (XEN)    00000000 0026cfb8 00000000 9e000000 00000000 00000000 00000000 c0000000
    (XEN)    00000000 ae000000 00000000 c0000000 00000000 00000000 00000018 00000000
    (XEN)    0000001a 00000000 aec00000 aea00000 ae800000 00400000 0020044c 00000000
    (XEN)    00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    (XEN)    00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    (XEN)    00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    (XEN)    00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    (XEN)    00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    (XEN)    00000000
    (XEN) Xen call trace:
    (XEN)    [<00271038>] cpu_stopmachine_init+0x80/0x110 (PC)
    (XEN)    [<0027102c>] cpu_stopmachine_init+0x74/0x110 (LR)
    (XEN)    [<00270098>] do_initcalls+0x4c/0x70
    (XEN)    [<0027a590>] start_xen+0xb44/0xde4
    (XEN)    [<0020044c>] paging+0x94/0xd8
    (XEN)
    (XEN)
    (XEN) ****************************************
    (XEN) Panic on CPU 0:
    (XEN) CPU0: Unexpected Trap: Data Abort
    (XEN)
    (XEN) ****************************************
    (XEN)
    (XEN) Reboot in five seconds...

**Comment by talex5** [comment]
I'm guessing this is related to the U-Boot update. I think @Furao had it working at one point - did something change?

**Comment by vitcozzolino** [comment]
Ok, I've made another test with the pre-built image but this time I also plugged in the serial cable that I just bought to have a look at the output. It is actually working, can login and everything even tho some basic modules are missing in the image, but that's another problem. I was mislead by the absence of blinking LEDs and no output on both HDMI/VGA.

**Comment by talex5** [comment]
Ah, great - thanks for following up!
