### ISSUE TITLE
[Xen on Cubietruck] How to see console with HDMI cable

### ISSUE THREAD

**Issue by samsunghoteltv** [mirage/xen-arm-builder#66]
After solving the #64 , I want to see Guest OS in GUI mode.
So I installed the ubuntu-dektop on Host OS, but some errors have been found.

any idea to see the monitor??

**Comment by mor1** [comment]
Hi; In testing the recent refresh I was actually using HDMI cable to a screen to see console output :) I'll go ahead and close this one, but if there's still an issue here, please do reopen.
