### ISSUE TITLE
Cubietruck Image - Issues with LAN connectivity

### ISSUE THREAD

**Issue by vitcozzolino** [mirage/xen-arm-builder#67]
Hi,
I'm having an hard time trying to access Internet from my CT with your distro. At the moment my only option is the LAN cable considering that all modules for WIFI adapters are not present in the distro. Anyway even with the LAN cable I'm not able at all to access the Internet: I'm getting my IP from the DHCP server but I'm not able to ping any end-point or even the gateway. With the same configuration, but with a different distro, I can normally access the web or ping any other device on the network without any kind of problem.

**Comment by mor1** [comment]
I've not had any problems with Internet connectivity after the recent refresh to Alpine. I'll go ahead and close this, but please reopen if you still experience the issue. Thanks!
