### ISSUE TITLE
Links to pre-built binaries are outdated/invalid

### ISSUE THREAD

**Issue by Hiradur** [mirage/xen-arm-builder#69]
The download links to the pre-built binaries in README.md are invalid.

**Comment by mor1** [comment]
Unfortunately, yes -- I believe they have been for some time. AFAIK @avsm is the only person who can rectify this, and he's off-grid this week. Slightly longer term, we'd like to move them to more reliable hosting anyway.

**Comment by mhsu0020** [comment]
Can somebody upload the cubietruck/cubieboard pre-built binaries to another mirror?

**Comment by mhsu0020** [comment]
FWIW I uploaded the two imgs I compiled from source. Use at your own risk:

[cubieboard2.tar](https://mega.nz/#!YggnhbSB)

[cubietruck.tar](https://mega.nz/#!50BEWL4Q)

**Comment by mor1** [comment]
After the refresh we're looking again at hosting images. The README will be updated when we sort that out. In the meantime, I'll close this issue. Thanks!
