### ISSUE TITLE
Xen on CubieTruck Plus ? (aka Cubieboard 5)

### ISSUE THREAD

**Issue by laurentgrangeau** [mirage/xen-arm-builder#70]
Hello there,

I was wondering if the new CubieTruck Plus was able to support the installation of Xen with the same instructions you write for strandard Cubietruck ?

**Comment by mor1** [comment]
It should be possible to try this with something like

```
TARGET=Cubietruck_plus \
DTB=src/linux-stable/arch/arm/boot/dts/sun8i-a83t-cubietruck-plus.dtb \
make all
```

I'm afraid I don't have a CBT+ to try the result out on, but I'm giving the above command a shot to see if it completes successfully anyway.

**Comment by mor1** [comment]
@laurentgrangeau Ok-- I ran the command above, and it seemed to complete successfully, building an apparently viable `sdcard.img`. As I don't have a device to test it on, I'll close this issue now but please do reopen if the resulting image turns out not to work! Thanks!
