### ISSUE TITLE
[xen on cubietruck @talex5] VGA/HDMI crashes on booting

### ISSUE THREAD

**Issue by ettchh** [mirage/xen-arm-builder#76]
The VGA/HDMI display working normally on booting U-boot and after "Starting kernel" it crashes and only I can see the output through uhart connection with cubietruck and I need to see the output on VGA/HDMI.
anyone can help please ?

**Comment by mor1** [comment]
That's a new one on me!
Can you provide any more info on what you mean by "it crashes"?
I would guess it's a kernel config build option-- did you change any from those in the repo?

**Comment by ettchh** [comment]
I think I made something wrong with steps 2 and 4 here https://github.com/talex5/xen-arm-builder
can you please tell me the steps to do it ?
I'm using ubuntu virtual machine 
after I cloned this repository these are my steps:
1- export Board=cubietruck
2- make clone
3- make build -> error:  
include/linux/compiler-gcc.h:106:30: fatal error: linux/compiler-gcc5.h: No such file or directory
so I added compiler-gcc5.h to this directory and $make build again and it passed but no VGA display, only UHART console 

I skipped the sunxi instruction because I didn't understand how to make it work
@mor1 any help or any further details to make it work right ?

**Comment by ettchh** [comment]
anyone can help me building the linux kernel right to avoid that crashing output ?
@mor1 @talex5

**Comment by mor1** [comment]
Sorry for taking so long - missed this! If you cloned from talex5 repo, then it seems that's a considerable way (77 commits?) behind this one. I reworked the process in this repo to use Docker so as to encapsulate the external deps, which hopefully simplifies the process a bit.

I'll close this issue as it's not actually relevant to the current state of the repo, but do reopen it if you try with the current `HEAD` of this repo and still experience the same problems.
